production:
  adapter: redis
#  url: <%#= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  url: redis://redistogo:5a517ff8ca7f7a250c641754e80906d7@scat.redistogo.com:10837/
#  channel_prefix: chat_app_production

development:
  adapter: async

test:
  adapter: test